language: node_js
node_js: 12.16.1

addons:
  apt:
    packages:
      - libgconf-2-4

install:
  - npm install
cache:
  npm: true
  directories:
    - ~/.npm

script:
  - npm run build

deploy:
  provider: netlify
  site: 6a440021-50a5-4e6a-ab41-39106fdcc18d
  auth: ie1lOnuqWU-yzmAO5diN9L1cXOdrmG4ocYQE439PjrY
  edge: true
  dir: build
  prod: true
