version: '3.7'
services:
   react-prod:
      environment:
         - REACT_APP_API_URL="https://backendecommerce12.herokuapp.com/api"
      build:
         context: .
         dockerfile: DOCKERFILE-prod

      ports:
         - '1337:80'
