version: '3.9'
services: 
    reactapp:
        build: 
            context: .
            dockerfile: DOCKERFILE
        volumes: 
            - '.:/app'
            - '/app/node_modules'
        ports:
            - 3001:3000
        environment: 
            - CHOKIDAR_USEPOLLING=true