FROM node:14-alpine as build
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH 
COPY package*.json ./
RUN npm ci --silent 
RUN npm install react-scripts@4.0.1 -g silent 
COPY . ./ 
RUN npm run build 

# production env 
FROM nginx:stable-alpine 
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80 
CMD ["nginx", "-g", "daemon off;"]